### ISSUE TITLE
ValueError: Layer "model" expects 3 input(s), but it received 1 input tensors. 

### ISSUE THREAD

**Issue by JiaLonghao1997** [yuanwxu/corr-net-classify#1]
When we try to run at https://github.com/yuanwxu/corr-net-classify/blob/main/MBQC/dgcnn_mbqc_nnode.py, we got the following error.  How to deal with this error?
```
(GNN) [jialh@node6 MBQC]$ python dgcnn_mbqc_nnode.py
2023-04-18 15:45:34.150380: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-18 15:45:34.703914: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-04-18 15:45:34.704484: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-18 15:45:44.301713: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
DGCNN Run 1 ...
WARNING:tensorflow:From /home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:648: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Use fn_output_signature instead
2023-04-18 15:46:05.605591: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2023-04-18 15:46:08.826639: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2023-04-18 15:47:46.377760: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
Test Set Metrics: 
	loss: 0.0065
	accuracy: 0.9937
	precision: 0.9937
	recall: 0.9937
	auc: 1.0000
2023-04-18 15:47:48.187136: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
Traceback (most recent call last):
  File "dgcnn_mbqc_nnode.py", line 183, in <module>
    main()
  File "dgcnn_mbqc_nnode.py", line 164, in main
    nn_imp = imp_calculator.nnode_imp(N) # N-node imp  ##报错: ValueError: Layer "model" expects 3 input(s), but it received 1 input tensors.
  File "/public/home/jialh/brain/01meta/multikingdom/06CACONET/corr-net-classify/MBQC/ImportanceDGCNN.py", line 203, in nnode_imp
    pred = self.predict_graph(sg)  ##这里出了问题。
  File "/public/home/jialh/brain/01meta/multikingdom/06CACONET/corr-net-classify/MBQC/ImportanceDGCNN.py", line 132, in predict_graph
    return self.model.predict(fl)
  File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filebg4yvwpa.py", line 15, in tf__predict_function
    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
ValueError: in user code:

    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/engine/training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/engine/training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/engine/training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/engine/training.py", line 2111, in predict_step
        return self(x, training=False)
    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home1/jialh/anaconda3/envs/GNN/lib/python3.8/site-packages/keras/engine/input_spec.py", line 219, in assert_input_compatibility
        raise ValueError(

    ValueError: Layer "model" expects 3 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None) dtype=float32>]
```

**Comment by yuanwxu** [comment]
Which versions of stellagraph, tensorflow and python did you use? Please use tensorflow 2.3.1 and python 3.8.2, and then install stellagraph:
`pip install -q --user stellargraph[demos]==1.2.1`

I think it might be due to incompatibility of packages. It runs on our machine.
